[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
fallback_oz = true
is_system = false 
mode = "3"

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]