#!/bin/bash

Include .env
export $(cat .env | xargs)

PRIVATE_KEY=$(cast wallet decrypt-keystore veggiaDeployer | grep "private key is: " | cut -d' ' -f5)
CALLER_ADDRESS=$(cast wallet address $PRIVATE_KEY)

echo "Running upgradeTo script as $CALLER_ADDRESS"

# Deploy VeggiaERC721 contract
# Parse result to get contract address using "Deployed to: " as delimiter
LOGIC_DEPLOYED_TO=$(forge create src/VeggiaERC721.sol:VeggiaERC721 \
    --private-key $PRIVATE_KEY \
    --rpc-url $ABSTRACT_TESTNET_URL \
    --chain 11124 \
    --zksync \
    --verify \
    --verifier zksync \
    --verifier-url https://api-explorer-verify.testnet.abs.xyz/contract_verification \
    --constructor-args $FEE_RECEIVER $VEGGIA_BASE_URI | grep "Deployed to: ")

# Extract implementation address
LOGIC_ADDRESS=$(echo $LOGIC_DEPLOYED_TO | cut -d' ' -f3)

# Deploy 
echo "Deployed VeggiaERC721 contract to address: $LOGIC_ADDRESS"

# Call proxy admin upgradeAndCall function
cast send $PROXY_ADMIN "upgradeAndCall(address,address,bytes)" $VEGGIA_ERC721 $LOGIC_ADDRESS 0x --rpc-url $ABSTRACT_TESTNET_URL --zksync --private-key $PRIVATE_KEY